apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: my-new-accelerator
spec:
  git:
    url: https://github.com/pdeshmuk/web-app-accelerator 
    ref:
      branch: main
